module.exports = [
  "The people with the most power make the least sacrifice.",
  "If you or I traded like Nancy Pelosi, we’d be in jail. But when she does it? It's called the Free Market.",
  "Insider trading isn’t just a crime — it’s a privilege for the powerful.",
  "They call it ‘public service’—we call it profiting off the people.",
  "Real change doesn’t come from within the system. It comes from exposing the system.",
  "Corruption isn’t a bug in the system. It is the system.",
  "They write the rules — and then rewrite them when they get caught.",
  "Millions live paycheck to paycheck, while politicians flip stocks before the public gets the news.",
  "Transparency isn’t radical. It's necessary.",
  "The market isn't rigged. It's just rigged against you.",
  "The same laws that jail a trader reward a politician.",
  "They don’t serve the people. They serve portfolios.",
  "They make the rules. Then break them. Then profit from the silence.",
  "You can’t fix corruption with silence. Only light drives out darkness.",
  "We don’t hate the system. We hate how it's abused.",
  "There’s no greater scam than ‘public servants’ becoming millionaires in office.",
  "Freedom without accountability is just a slogan.",
  "Information is power. That’s why they hide it.",
  "This isn’t about politics. It’s about power and profit.",
  "When truth threatens power, power tries to silence it.",
  "We’re not here to burn it down. We’re here to clean it up.",
  "No revolution is needed when accountability exists.",
  "They fear exposure more than regulation.",
  "Let the facts speak louder than the headlines.",
  "When justice is selective, it isn’t justice at all.",
  "We’re not conspiracy theorists—we’re data analysts with receipts.",
  "A country built on democracy should not protect oligarchy.",
  "Every transaction tells a story. We’re just reading it aloud.",
  "If they weren’t hiding anything, they’d welcome the transparency.",
  "Truth doesn’t scream. It posts quietly, every day, until people wake up.",
  "Our movement is peaceful—but persistence is powerful.",
  "We won't riot. We’ll reveal.",
  "Let the people decide—with real data, not filtered news.",
  "Sunlight is still the best disinfectant.",
  "We post not to stir fear, but to spark focus.",
  "A dollar earned is not the same as a dollar exploited.",
  "Change doesn’t come from tweets—it comes from sustained truth.",
  "We expose, we don't explode.",
  "It’s not left vs. right—it’s top vs. everyone else.",
  "If insider trading were enforced equally, Congress would be empty.",
  "Ethics should not be optional for lawmakers.",
  "We aren’t demanding vengeance—just verification.",
  "Silence helps no one but the guilty.",
  "They call it 'smart investing'—we call it insider advantage.",
  "How many fortunes were made before you got the news?",
  "The system isn’t broken. It’s working exactly as designed—for them.",
  "They cashed in on chaos while we scrambled to survive.",
  "This isn’t hate. It’s hope with receipts.",
  "They’re not untouchable. Just unchallenged—until now.",
  "You deserve better than manipulated markets and media silence.",
  "We’re not anarchists—we’re analysts. And the data is damning.",
  "Expose the rot. Inspire the fix. Demand the reform.",
];
